import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Suspense } from "react";
import { Profile } from "@/app/_components/Profile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Home / SNS</title>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link rel="icon" href="favicon.png" />
      </head>
      <body>
        <div className="layout_wrapper">
          <nav>
            <div className="nav_logo-wrapper">
              <p className="nav_logo">SNS</p>
            </div>

            <div className="menu_options active">
              <span className="material-icons">home</span>
              <h2>ホーム</h2>
            </div>

            <div className="menu_options">
              <span className="material-icons">search</span>
              <h2>検索</h2>
            </div>

            <div className="menu_options">
              <span className="material-icons">notifications</span>
              <h2>通知</h2>
            </div>

            <div className="menu_options">
              <span className="material-icons">email</span>
              <h2>メッセージ</h2>
            </div>

            <div className="menu_options">
              <span className="material-icons">bookmark</span>
              <h2>ブックマーク</h2>
            </div>

            <div className="menu_options">
              <span className="material-icons">person</span>
              <h2>プロフィール</h2>
            </div>

            <div className="menu_options">
              <span className="material-icons">more_horiz</span>
              <h2>もっと見る</h2>
            </div>

            <button className="post_btn">ポストする</button>

            <div className="side_profile">
              <Suspense fallback={<div>loading...</div>}>
                <Profile size="lg" hasName />
              </Suspense>
            </div>
          </nav>
          {children}
          <aside>
            <div className="aside_input">
              <span className="material-icons aside_search-icon">search</span>
              <input type="text" placeholder="検索" />
            </div>

            <div className="aside_container">トレンド</div>
          </aside>
        </div>
      </body>
    </html>
  );
}
